# 数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_study_demo01
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true